### ISSUE TITLE
No MQ messages

### ISSUE THREAD

**Issue by editter** [kind3r/hass-addons#23]
Hello, I set up the addon in a second instance on a raspberry pi 3 and got the lock connected but I never see any MQ messages come through.  I am not seeing the "MQTT connected" message in the logs so something isn't working but I'm not sure why.  I get my birth/will messages when HA starts/stops so I know the MQ stuff is working but nothing from this addon.  Thoughts?

Here is my entire configuration.yaml (note I did try adding the default_config entry in case that was important but I didn't see anything different)

configuration.yaml
```yaml
config:
frontend:
hassio:
http:
webhook:

mqtt:
  discovery: false
  discovery_prefix: hass2
  birth_message:
    topic: "hass2/status"
    payload: "online"

  will_message:
    topic: "hass2/status"
    payload: "offline"
  broker: 192.168.1.55
  port: 1883
  client_id: hass2
  username: !secret mqtt_username
  password: !secret mqtt_password
```
